### ISSUE TITLE
GL_ARB_timer_query not supported on MacOS X

### ISSUE THREAD

**Issue by hasseily** [aiekick/InAppGpuProfiler#1] opened 2024-07-16 14:05 UTC
I tried using IAGP in my project as well as the DemoApp, and I'm not seeing any of the breadcrumbs appear in the flame graph. It's just empty. I can click on details but I only see the top level.
I'm investigating. At this point I'm seeing errors in:
`glGetQueryObjectuiv(id, GL_QUERY_RESULT_AVAILABLE, &value);`
The second id pushed onto `m_PendingUpdate` does not like `glGetQueryObjectuiv`.

**Comment by hasseily** [comment] 2024-07-16 14:15
Scratch that. Problem happens independently of ImGUI version. Even the DemoApp on 1.89 has the same issue.
![Screenshot 2024-07-16 at 17 15 00](https://github.com/user-attachments/assets/407e70b9-1914-47a8-b191-990272a8f368)

**Comment by aiekick** [comment] 2024-07-16 15:11
hello,

thanks for the report.

will check that.

seems to be a bug i fixed in the vk version.

need to find the time for get a common version gl/vk

**Comment by aiekick** [comment] 2024-07-16 18:04
its working on my side...

![image](https://github.com/user-attachments/assets/d3b96ddc-fe76-4060-b9ca-88d90977cd76)

do you have some opengl errors printed in your console ??

what version of opengl are you using ? what gpu ? what driver version ?

**Comment by hasseily** [comment] 2024-07-16 18:58
Yes I get the one error at the root, the 2nd item in the `m_PendingUpdate` vector. Which is why the tree probably doesn't display.

```------ Collect Thread (41326448) -----
IAGP glGetQueryObjectuiv error: 1282
 id not retrieved : 2
  end id retrieved : 4
   end id retrieved : 6```
   
   I'm on OpenGL 4.1 Metal - 88.1

**Comment by hasseily** [comment] 2024-07-16 19:01
This is what it looks like
![Screenshot 2024-07-16 at 22 00 33](https://github.com/user-attachments/assets/f8902e7e-ee62-47e9-af78-e4e94f9a41f3)

**Comment by aiekick** [comment] 2024-07-16 19:22
so its not related to ImGui but to Opengl.

> ```
> IAGP glGetQueryObjectuiv error: 1282
> ```

who is emitting this log ? its not from the code of IAGP.

Please check console errors in debug mode with the DemoApp. 
I cant analyse your opengl use in your soft. 
if this is a bug of my lib, he must be identified in the DemoApp.

your details is empty since you have no opengl queries retrieved. so its normal.

FYI, the error 1282 is INVALID_OPERATION so maybe the glGetQueryObjectuiv use a bad id.

the issue is related to glGetQueryObjectuiv.

**Comment by hasseily** [comment] 2024-07-16 19:26
I added this debugging to see where the OpenGL error was. I get the exact same problem with DemoApp. I can test DemoApp with full debugging as well. Give me a moment to put in the additional debug

**Comment by hasseily** [comment] 2024-07-16 19:43
Interesting. I don't see any GL errors in DemoApp but I still don't see anything.
![Screenshot 2024-07-16 at 22 42 24](https://github.com/user-attachments/assets/61eced76-bfde-4de5-8264-609592640fbb)

**Comment by aiekick** [comment] 2024-07-16 20:47
ok its weird, since i have tested the DemoApp on windows and linux. 
And not seen any issues since long time ago. but tested only with nvidia and RTX3060. opengl 4.6

**Comment by hasseily** [comment] 2024-07-17 08:20
I've gotten through the issue. The problem is that the `GL_ARB_timer_query` extension, which has `glQueryCounter`, is not supported on MacOS X.
Hence, start and finish times are 0 and there's no ability to drill down into the tree.
Feel free to close this issue. This is quite unfortunate.

**Comment by hasseily** [comment] 2024-07-17 09:50
I created a pull request that uses CPU timers for OS X. #2

**Comment by aiekick** [comment] 2024-07-17 10:08
hello,

ok.. but iago is a GPU profiler not a CPU profiler.

**Comment by aiekick** [comment] 2024-07-17 10:35
> The problem is that the `GL_ARB_timer_query` extension, which has `glQueryCounter`, is not supported on MacOS X. 

Too bad.. 

btw thanks for the PR. we will discuss on it now

**Closed as completed by aiekick** 2024-07-17 10:35 UTC
Labels: bug
